CREATE TABLE `app_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`app_key` varchar(64) NOT NULL,
	`app_name` varchar(120) NOT NULL,
	`app_url` varchar(500) NOT NULL,
	`signup_url` varchar(500),
	`emoji` varchar(8) NOT NULL DEFAULT '🌐',
	`category` varchar(32) NOT NULL DEFAULT 'learning',
	`status` enum('not_started','pending_email_verify','pending_family_link','active','needs_reset','closed') NOT NULL DEFAULT 'not_started',
	`sign_in_email` varchar(320),
	`sign_in_username` varchar(200),
	`password_encrypted` text,
	`password_iv` varchar(64),
	`notes` text,
	`has_family_tier` boolean NOT NULL DEFAULT false,
	`is_paid` boolean NOT NULL DEFAULT false,
	`monthly_cost` int,
	`sort_order` int NOT NULL DEFAULT 0,
	`last_verified_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `app_accounts_id` PRIMARY KEY(`id`),
	CONSTRAINT `app_accounts_app_key_unique` UNIQUE(`app_key`)
);
