/**
 * Twelve reference Markdown docs that get pushed to canonical Drive
 * subfolders so Mom, Dad, Grandma, and any tutor can read them inside
 * Drive without needing to log into the dashboard.
 *
 * Each doc is a pure builder (no DB/IO) — the file body is fully
 * deterministic given the dateISO + dashboardUrl seed. The enqueuer
 * inserts a `drivePushQueue` row per doc, idempotent on contentText
 * match (same body already pending for the same path → no-op). The
 * Drive worker drains the queue and writes the actual files.
 *
 * Coverage map (12 docs):
 *   1.  Ohio 5th-Grade Scope & Sequence (curriculum_checklist)
 *   2.  Ohio IH Annual Portfolio — How To (report_cards)
 *   3.  Weekly Cadence at a Glance (daily_schedule)
 *   4.  Khan Academy: What Maps Where (apps_tools)
 *   5.  IXL: What Maps Where (apps_tools)
 *   6.  Kiwi the Mascot — Tap Cheatsheet (kiwi_coins)
 *   7.  Adult Quick-Entry — One-Tap Logging (adult_notes)
 *   8.  Recap Email — How To Reply (recap_reply)
 *   9.  Day Log Format — What's In Each File (day_log)
 *   10. Tutor Handoff Template (tutor)
 *   11. Bookshelf & Reading Log Conventions (bookshelf)
 *   12. Adventures: Outdoor Block Playbook (adventures)
 */

export type DriveReferenceDoc = {
  /** Stable slug used for dedupe lookups. */
  slug: string;
  /** drivePushQueue.target_folder enum value. */
  targetFolder: string;
  /** subfolder under the target (kept stable; not date-bucketed). */
  targetSubpath: string;
  /** Filename, including extension. */
  fileName: string;
  /** Markdown body (deterministic given seed). */
  content: string;
};

export type DriveReferenceSeed = {
  generatedAtISO?: string;
  dashboardUrl?: string;
};

const FOOTER = (generatedAtISO: string, dashboardUrl: string) =>
  `\n\n---\n*Generated by Reagan's Homeschool Dashboard on ${generatedAtISO}. ` +
  `Live source of truth: ${dashboardUrl}*\n`;

/**
 * Build all 12 reference docs as pure values. Order is stable so tests
 * can index by position. No DB, no env, no time (caller passes seed).
 */
export function buildDriveReferenceDocs(seed: DriveReferenceSeed = {}): DriveReferenceDoc[] {
  const generatedAtISO = seed.generatedAtISO ?? new Date().toISOString().slice(0, 10);
  const dashboardUrl = seed.dashboardUrl ?? "https://reagan-homeschool-dashboard.manus.space";
  const f = FOOTER(generatedAtISO, dashboardUrl);

  return [
    // 1. Ohio 5th-Grade Scope & Sequence
    {
      slug: "ohio-5th-scope",
      targetFolder: "curriculum_checklist",
      targetSubpath: "Reference",
      fileName: "Ohio 5th-Grade Scope and Sequence.md",
      content:
`# Ohio 5th-Grade Scope and Sequence

## Math (8 ladder strands)
- **NBT** Number & Operations in Base Ten — multi-digit multiplication, decimal place value, decimal operations.
- **NF** Number & Operations — Fractions — add/subtract/multiply/divide fractions, mixed numbers.
- **OA** Operations & Algebraic Thinking — order of operations, numerical expressions, patterns.
- **MD** Measurement & Data — volume of rectangular prisms, line plots, unit conversion.
- **G** Geometry — coordinate plane, attributes of 2-D figures, classification.

## English Language Arts (6 ladder strands)
- **RL** Reading Literature — theme, character, point of view.
- **RI** Reading Informational — main idea, multiple texts, evidence-based claims.
- **W** Writing — opinion, informative, narrative; multi-paragraph structure.
- **L** Language — conventions, vocabulary, figurative language.
- **SL** Speaking & Listening — collaborative discussion, presentations.
- **F** Foundational Skills — phonics carryover for fluency.

## Science (4 ladder strands)
- **PS** Physical Science — light, sound, matter & energy.
- **LS** Life Science — ecosystems, interdependence, structures and processes.
- **ESS** Earth & Space Science — weather, water cycle, solar system.
- **ETS** Engineering, Tech & Applications — design process.

## Social Studies (4 ladder strands)
- **HIS** History — Western Hemisphere, early civilizations.
- **GEO** Geography — physical, human, environment.
- **CIV** Civics & Government — democratic principles, citizenship.
- **ECON** Economics — markets, scarcity, productive resources.

## How this maps in the dashboard
Every assignment carries a **skill code** (e.g. \`OH.5.NBT.3\`) that matches one row in the skill ladder. The Today page, Practice page, Schedule auto-attach, and Summer Mode review queue all read from the same ladder so progress in any surface counts everywhere.${f}`,
    },
    // 2. Ohio IH Annual Portfolio — How To
    {
      slug: "ohio-ih-portfolio",
      targetFolder: "report_cards",
      targetSubpath: "Reference",
      fileName: "Ohio Independent Homeschool Portfolio Guide.md",
      content:
`# Ohio Independent Homeschool — Annual Portfolio Guide

Ohio Revised Code 3321.042 requires a year-end **academic assessment** for kids homeschooled under the IH (Independent Home Education) statute. The dashboard collects everything you need.

## What goes in the portfolio
1. **Topics covered list** — generated from the 5th-grade Report Card (page \`/report-card/5\` in the dashboard). The "Completed Topics" rollup is sourced from \`skillProgress.lastPracticedAt\` for any ladder row at level ≥ 4.
2. **Sample work** — pulled from the \`Finished Work\` Drive folder (organized by month).
3. **Day logs** — the \`Day Logs/{YYYY-MM}/\` folder is your day-by-day record.
4. **Books read** — the Bookshelf page exports a yearly reading log.
5. **Adult notes / observations** — the \`Adult Notes\` Drive folder.

## Annual review options
You can satisfy the assessment requirement with **any** of:
- A signed letter from a licensed Ohio teacher who has reviewed the portfolio.
- A nationally normed standardized test result.
- An alternative academic assessment agreed to by the superintendent.

## Tip
Run **Print 5th-Grade Report Card** in the dashboard at year-end. The PDF includes overall mastery %, per-subject ladder rollup, and the dated completed-topics list — that PDF is the spine of the portfolio.${f}`,
    },
    // 3. Weekly Cadence at a Glance
    {
      slug: "weekly-cadence",
      targetFolder: "daily_schedule",
      targetSubpath: "Reference",
      fileName: "Weekly Cadence at a Glance.md",
      content:
`# Weekly Cadence at a Glance

The dashboard auto-attaches a balanced subject mix to every weekday. Reagan's typical week:

| Day | Math | ELA | Science | SS | Movement / Adventure |
| --- | ---- | --- | ------- | -- | -------------------- |
| Mon | core | core | — | core | gym block |
| Tue | core | core | core | — | adventure block |
| Wed | core | core | — | core | art / hands-on |
| Thu | core | core | core | — | adventure block |
| Fri | review | review | review | review | field-trip-friendly |

## Saturdays
Light review only — Summer Mode pulls one math + one ELA review block, capped at 45 minutes total.

## Sundays
**No school**. The nightly weekly digest email lands Sunday evening with last week's progress + what's planned for the week ahead.

## Day cap
Hard cap of **10 blocks** and **300 minutes** per day, enforced by \`sanitizeBlocks\`. The AI agenda chat will refuse to insert past those caps.${f}`,
    },
    // 4. Khan Academy mapping
    {
      slug: "khan-mapping",
      targetFolder: "apps_tools",
      targetSubpath: "Khan Academy",
      fileName: "Khan Academy — What Maps Where.md",
      content:
`# Khan Academy — What Maps Where

**Account:** spear.cpt@gmail.com (parent) — Reagan signs in via this account too.

## How dashboard topics map to Khan
| Dashboard ladder | Khan course | Notes |
| ---------------- | ----------- | ----- |
| OH.5.NBT.* | 5th grade math: Place value & decimals | All NBT codes covered. |
| OH.5.NF.* | 5th grade math: Fractions | Match by sub-strand. |
| OH.5.OA.* | 5th grade math: Algebraic thinking | Includes order of operations. |
| OH.5.MD.* | 5th grade math: Measurement & data | Volume unit is here. |
| OH.5.G.* | 5th grade math: Geometry | Coordinate plane unit. |
| OH.5.RL.* / RI.* | 5th grade reading & vocab | Khan splits literature vs informational. |
| OH.5.PS / LS / ESS | Middle school physics / biology / earth | 5th-grade Khan is thin; jump up. |

## How to log Khan time on the dashboard
- The Apps page card has **Student** and **Parent** sign-in buttons (Student = default).
- Time on Khan automatically counts toward the matching skill ladder row when you log it via Adult Quick-Entry.${f}`,
    },
    // 5. IXL mapping
    {
      slug: "ixl-mapping",
      targetFolder: "apps_tools",
      targetSubpath: "IXL",
      fileName: "IXL — What Maps Where.md",
      content:
`# IXL — What Maps Where

**Account:** spear.cpt@gmail.com (parent + student share). Inactive: \`reagan.higgs33@ihsd.us\`.

## IXL → ladder code lookup
| IXL skill code | Ladder code |
| -------------- | ----------- |
| 5.B.* | OH.5.NBT.* |
| 5.M.* | OH.5.NF.* |
| 5.O.* | OH.5.OA.* |
| 5.W.* | OH.5.MD.* |
| 5.X.* | OH.5.G.* |
| 5.RR.*, 5.SS.* | OH.5.RL.*, OH.5.RI.* |
| 5.WW.* | OH.5.W.* |

## Smart Score → Mastery band
- 80+ on IXL ≈ ladder level 4 (Mastered)
- 60-79 ≈ level 3 (Practicing)
- < 60 ≈ level 2 (Introduced)

The dashboard's Adult Quick-Entry "Did 20 min of IXL — got 85 on 5.B.7" parses the score into the correct ladder bump automatically.${f}`,
    },
    // 6. Kiwi mascot guide
    {
      slug: "kiwi-cheatsheet",
      targetFolder: "kiwi_coins",
      targetSubpath: "Reference",
      fileName: "Kiwi the Mascot — Tap Cheatsheet.md",
      content:
`# Kiwi the Mascot — Tap Cheatsheet

Kiwi (the green parrot in the bottom-right corner) is Reagan's friendly AI helper. He stays out of the way and only activates on tap.

## Taps
| Action | Result |
| ------ | ------ |
| Single tap on Kiwi | Opens the chat bubble — ask anything school-related. |
| Tap the **✈️ Fly!** button | Kiwi flies across the screen and back (just for fun). |
| Double-tap Kiwi | Same as Fly button (legacy). |
| Long-press Kiwi | Drag him to a different corner. |

## What Kiwi can do
- Answer school questions in kid-safe language.
- Read the day's agenda out loud.
- Summarize a worksheet in plainer English.
- Suggest a stretch break or movement game.
- Award **Kiwi Coins** for finishing a block (Mom approves redemption).

## What Kiwi WON'T do
- He never auto-opens.
- He never asks for microphone access without you tapping first.
- He never changes the schedule directly — Reagan can *request* changes via Kiwi, and Mom approves them on the Approvals page.${f}`,
    },
    // 7. Adult Quick-Entry
    {
      slug: "adult-quick-entry",
      targetFolder: "adult_notes",
      targetSubpath: "Reference",
      fileName: "Adult Quick-Entry — One-Tap Logging.md",
      content:
`# Adult Quick-Entry — One-Tap Logging

When Reagan does something off-plan (a museum visit, a board game that taught fractions, a surprise read-aloud) you don't need to redesign her schedule. Open **Adult Quick-Entry** from the sidebar and tap one of the chips.

## What gets logged
- **Topic Covered** — adds a row to the Topics Covered Drive folder (\`/Curriculum and Standards/Topics Covered/{YYYY-MM}/\`) and bumps the matching ladder row.
- **Off-Plan Block** — appends to today's Day Log; auto-attached to the correct subject if you mention one.
- **Reading Snippet** — pushes to the Bookshelf folder + counts toward the reading log.
- **Photo / Camera** — uploads from your phone, attaches to today's Day Log.

## How AI helps
Tap "Let AI clean this up" and the entry is rewritten as a tidy, dated paragraph suitable for the IH portfolio.

## Daily notes UI
Notes for adults reopen to the same page each day so you can keep adding observations through the day. The background is intentionally light for daytime readability.${f}`,
    },
    // 8. Recap reply
    {
      slug: "recap-reply-howto",
      targetFolder: "recap_reply",
      targetSubpath: "Reference",
      fileName: "Recap Email — How To Reply.md",
      content:
`# Recap Email — How To Reply

Every evening the dashboard sends a recap email to **marcy.spear@gmail.com** and **spear.cpt@gmail.com** summarizing the day. You can reply to that email and the dashboard will read your reply.

## What replies do
The recap reply parser looks for:
- **Topics actually covered** ("Reagan also did long division for 20 min")
- **Time tweaks** ("Skipped science today")
- **Observations** ("She struggled with fraction division — circle back tomorrow")

…and writes a Markdown file into:
\`/Daily Operations/Recap Replies/{YYYY-MM}/{date} - {sender} - Recap.md\`

## Behind the scenes
Replies flow through \`drivePushQueue\` like every other Drive write — fire-and-forget; the worker drains the queue. If you don't get a recap one evening, the dashboard sends a "What did Reagan do today?" follow-up the next morning.

## Where to read past recaps
Open the \`Daily Operations / Recap Replies\` Drive folder; everything is bucketed by month.${f}`,
    },
    // 9. Day Log Format
    {
      slug: "day-log-format",
      targetFolder: "day_log",
      targetSubpath: "Reference",
      fileName: "Day Log Format — Whats In Each File.md",
      content:
`# Day Log Format — What's In Each File

Every day produces one Markdown file: \`{date} - Day Log.md\`, written to:
\`/Daily Operations/Day Logs/{YYYY-MM}/\`

## Sections
1. **Header** — date, Reagan's mood (if she logged one), weather.
2. **Planned vs Actual** — the agenda we *meant* to do vs what got finished. Status flips on each block (Done / Partial / Skipped) appear here.
3. **Off-plan captures** — anything entered via Adult Quick-Entry.
4. **Time totals** — minutes per subject + total active learning time.
5. **AI Summary** — one paragraph the LLM writes from the day's signals (voice, activity, completion).
6. **Tomorrow** — auto-suggested follow-ups for the next school day.

## Re-generation
The day log is rebuilt every time anything changes for that date. Old versions are NOT preserved — Drive just gets the latest. (Past audits are still recoverable via the dashboard's version history.)

## Why a single Markdown file
Markdown opens cleanly in Drive's preview, copies into Google Docs without ceremony, and is easy for Mom or a future tutor to read on a phone.${f}`,
    },
    // 10. Tutor Handoff
    {
      slug: "tutor-handoff",
      targetFolder: "tutor",
      targetSubpath: "Reference",
      fileName: "Tutor Handoff Template.md",
      content:
`# Tutor Handoff Template

Use this when bringing a new tutor onto Reagan's homeschool, or for a one-off session.

## Before the session
- Tutor's email gets added as a guest on the day's Google Calendar event.
- Tutor receives a copy of the Day's Agenda PDF (auto-emailed if their address is in the dashboard).
- Today's blocks list which subjects are tutor-eligible.

## What the tutor needs
1. **The current ladder snapshot** — \`/report-card/5\` printable shows where Reagan is right now per subject and per strand.
2. **What we tried this week** — the last 5 day logs (Drive folder).
3. **What's stuck** — any ladder row that's been at level 2 for > 2 weeks needs a different approach.
4. **What to avoid** — the dashboard's "Adult Notes" folder includes any sensory or focus accommodations.

## After the session
The tutor replies to the recap email with what they covered. The dashboard parses it into the day log + bumps the right ladder row.

## Pay
Tutoring time is logged by Mom, not the tutor. Use Adult Quick-Entry → "Tutor Block" → enter minutes + tutor name.${f}`,
    },
    // 11. Bookshelf
    {
      slug: "bookshelf-conventions",
      targetFolder: "bookshelf",
      targetSubpath: "Reference",
      fileName: "Bookshelf and Reading Log Conventions.md",
      content:
`# Bookshelf and Reading Log Conventions

The Bookshelf page is Reagan's reading record. Every book she reads — out loud, silent, or read-to — gets a row.

## States
- **Reading** — currently in the middle of it.
- **Finished** — completed; counts toward the IH portfolio reading log.
- **Wishlist** — Mom or Reagan flagged it for later.

## Tags we standardize on
- \`fiction\` / \`nonfiction\`
- \`reagan-pick\` (she chose it) / \`assigned\` (curriculum)
- \`audiobook\` (still counts!)
- \`novel-in-verse\`, \`graphic-novel\`, \`chapter-book\`, \`picture-book\`
- \`series-name:WingsOfFire\` (or whichever)

## Daily reading logging
The Day Log auto-fills time spent reading from any \`reading\` block + any Bookshelf "session" entries. You don't double-count.

## Year-end export
Run "Export Reading Log" on the Bookshelf page; it produces a CSV + Markdown summary in this folder, ready for the IH portfolio.${f}`,
    },
    // 12. Adventures
    {
      slug: "adventures-playbook",
      targetFolder: "adventures",
      targetSubpath: "Reference",
      fileName: "Adventures — Outdoor Block Playbook.md",
      content:
`# Adventures — Outdoor Block Playbook

Adventure blocks are the dashboard's name for movement-rich, hands-on learning. They're built by \`buildAdventureBlock()\` and always include a **materials list**, **numbered steps**, and an **outdoor option**.

## Why
- Ohio's IH statute counts physical education and applied learning toward instructional time.
- Reagan focuses better with at least one big-movement block per day.
- Outdoor adventures double as the day's gym block.

## Standing themes
- **Nature** — birding, leaf ID, weather observations.
- **Maker** — build, sew, cardboard engineering.
- **Movement** — geocaching, parkour drills, running games.
- **Community** — library trip, museum, farmer's market.

## Logging
On finish, tap the block → "Done". The day log auto-pulls the materials list + the outdoor option taken (or not). Photos taken in the moment can be attached via Adult Quick-Entry → Photo.

## Safety
- The outdoor option is opt-in; default is the indoor backup.
- Any block with \`outdoor: true\` requires Mom-tap "I'll be outside" before Reagan sees the GO button.${f}`,
    },
  ];
}

export type EnqueueDriveReferenceDocsResult = {
  ok: boolean;
  enqueued: number;
  skippedAlreadyQueued: number;
  failed: number;
};

/**
 * Enqueue all 12 reference docs into drivePushQueue. Idempotent on
 * (target_folder, target_subpath, file_name, contentText) — re-running
 * with the same seed is a safe no-op. Fire-and-forget; never throws.
 */
export async function enqueueDriveReferenceDocs(
  seed: DriveReferenceSeed = {},
): Promise<EnqueueDriveReferenceDocsResult> {
  const docs = buildDriveReferenceDocs(seed);
  let enqueued = 0;
  let skippedAlreadyQueued = 0;
  let failed = 0;
  try {
    const [{ getDb }, schemaMod, drizzle] = await Promise.all([
      import("../db"),
      import("../../drizzle/schema"),
      import("drizzle-orm"),
    ]);
    const drivePushQueue = (schemaMod as any).drivePushQueue;
    const { and, eq } = drizzle as any;
    const db = getDb();

    for (const doc of docs) {
      try {
        let alreadyQueued = false;
        try {
          const existing: any[] = await db
            .select()
            .from(drivePushQueue)
            .where(
              and(
                eq(drivePushQueue.targetFolder as any, doc.targetFolder as any),
                eq(drivePushQueue.fileName as any, doc.fileName as any),
                eq(drivePushQueue.status as any, "pending" as any),
              ),
            );
          if (existing.some((r: any) => r?.contentText === doc.content)) {
            alreadyQueued = true;
          }
        } catch {
          // best-effort dedupe; fall through
        }
        if (alreadyQueued) {
          skippedAlreadyQueued += 1;
          continue;
        }
        await db.insert(drivePushQueue).values({
          targetFolder: doc.targetFolder as any,
          targetSubpath: doc.targetSubpath,
          fileName: doc.fileName,
          mimeType: "text/markdown",
          contentText: doc.content,
          status: "pending" as any,
        } as any);
        enqueued += 1;
      } catch (e) {
        failed += 1;
        console.warn(
          `[enqueueDriveReferenceDocs] failed for ${doc.slug}`,
          (e as any)?.message ?? e,
        );
      }
    }
    return { ok: true, enqueued, skippedAlreadyQueued, failed };
  } catch (e: any) {
    console.warn("[enqueueDriveReferenceDocs] fatal", e?.message ?? e);
    return { ok: false, enqueued, skippedAlreadyQueued, failed: docs.length - enqueued - skippedAlreadyQueued };
  }
}
